using System;
using System.IO;
using Api.Collector.Metadata.Api;
using Newtonsoft.Json;

namespace Api.Collector.Swagger
{
    public class SwaggerApiGenerator
    {
        public void Generate(ApiCollectorResult result, String autogeneratedJsonPath, ApiRoot apiRoot)
        {
            foreach (var apiBundle in result.ApiBundles)
            {
                apiRoot.Apis.AddRange(apiBundle.Apis);
            }

            File.WriteAllText(autogeneratedJsonPath, JsonConvert.SerializeObject(apiRoot, Formatting.Indented));
        }
    }
}