using System.IO;
using Api.Collector.Metadata.Api;
using Newtonsoft.Json;

namespace Api.Collector.Swagger
{
    public class SwaggerApiGenerator
    {
        public void Generate(ApiCollectorResult result)
        {
            ApiRoot apiRoot = new ApiRoot
            {
                ApiVersion = "1.8",
                SwaggerVersion = "1.1",
                BasePath = "/",
                ResourcePath = "/generated_by_controllers"
            };

            
            foreach (var apiBundle in result.ApiBundles)
            {
                apiRoot.Apis.AddRange(apiBundle.Apis);
            }

            File.WriteAllText(@"..\..\..\..\..\Services\Services\Api\api-docs\internal\autogenerated.json", JsonConvert.SerializeObject(apiRoot, Formatting.Indented));
        }
    }
}